#!/usr/bin/env bash
# dsh-graph client.js 构建脚本（g-319：产物输出到 dist/）
# 将 dsh-graph-host/lib/client/ 目录下的子模块拼接组装为 dist/lib/client.js
#
# 用法：从仓库根目录运行 bash scripts/build-client.sh
#
# 可重定向（g-348，默认值与独立调用契约不变）：DIST_DIR 为产物根目录，默认 dist/。
# build.sh 把它指向原子发布暂存区，使发布前 dist/ 不被触碰。
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="${DIST_DIR:-dist}/lib/client.js"
MOD="dsh-graph-host/lib/client"

mkdir -p "$(dirname "$OUT")"

PARTS=(
  "_wrapper-top"
  "i18n"
  "constants"
  "helpers"
  "session-hooks"
  "live-panel"
  "supervisor-bar"
  # [autopilot-fork] 自动驾驶面板（工厂作用域组件，kanban.js 渲染引用；必须在 drag-prompts 之前）
  "autopilot"
  "card"
  "markdown"
  "card-drawer"
  "goal-actions"
  "goal-modal"
  "criteria-modal"
  # g-255：搜索临时可见性状态机纯函数模块，kanban.js 依赖其导出函数；
  # 必须排在 drag-prompts 之前（drag-prompts 打开 KanbanView 函数体，之后的代码
  # 在 KanbanView 局部作用域内；search-state 函数需在工厂作用域定义以被 KanbanView 引用）
  "search-state"
  # g-290：retained 明细对账纯函数模块（修复 backlog/released 成员变化被旧明细掩盖的
  # 幽灵卡片缺陷），kanban.js load() 依赖其导出函数；与 search-state 同理必须排在
  # drag-prompts 之前（工厂作用域），否则会变成 KanbanView 内部的嵌套函数。
  "board-retain"
  # g-352：窄宽度响应式派生纯函数模块（断点分档/单版本投影/排期目标选项）。
  # 与 search-state、board-retain 同理必须排在 drag-prompts 之前（工厂作用域），
  # 否则会变成 KanbanView 内部的嵌套函数。
  "narrow-width"
  # g-367：搜索命中按版本/分区聚合纯函数模块（组序/分桶；窄档聚合泳道的组头与计数）。
  # 与 search-state、board-retain、narrow-width 同理必须排在 drag-prompts 之前（工厂作用域），
  # 否则会变成 KanbanView 内部的嵌套函数。
  "search-groups"
  # g-243：version-drawer 必须排在 drag-prompts 之前（工厂作用域），不能夹在
  # drag-prompts 与 kanban 之间——drag-prompts 打开 KanbanView 函数体、kanban 收尾，
  # 夹在中间会让 VersionDrawer 变成 KanbanView 内部的嵌套函数：每次 KanbanView 渲染
  # 都会产生新的函数身份，React 因 elementType 变化卸载重建抽屉子树，版本清单
  # scrollTop 随之归零（勾选/取消 checkbox 或看板刷新后跳回第一行）。
  "version-drawer"
  # g-273：批量接受模块（纯函数 + BatchAcceptModal 组件）必须在 drag-prompts 之前
  # （工厂作用域），与 version-drawer 同理——夹在 drag-prompts 与 kanban 之间会变成
  # KanbanView 内部嵌套函数，每次渲染产生新组件身份导致 React 卸载重建弹窗子树。
  "batch-accept"
  "drag-prompts"
  "kanban"
  "shared-panel"
  "settings-modal"
  "settings"
  "plugin"
  "_wrapper-bottom"
)

# 写入稳定的生成标记 header
cat > "$OUT" << 'EOF'
// ⚠️ GENERATED FILE — DO NOT EDIT DIRECTLY
// This file is auto-generated by scripts/build-client.sh
// To modify, edit the source modules in dsh-graph-host/lib/client/*.js
// and run: bash scripts/build-client.sh
EOF

# 拼接所有模块（剥离 ESM export 块，因为客户端 bundle 是工厂作用域拼接，不是 ESM）
for part in "${PARTS[@]}"; do
  file="$MOD/${part}.js"
  if [ ! -f "$file" ]; then
    echo "ERROR: 缺少子模块 $file" >&2
    exit 1
  fi
  # 去掉 ESM export 块（搜索纯函数模块等为测试导出的接口，浏览器 bundle 不需要）
  sed '/>>>ESM-EXPORTS-START>>>/,/<<<ESM-EXPORTS-END<<</d' "$file" >> "$OUT"
done

LINES=$(wc -l < "$OUT")
echo "✅ client.js 已组装完成 ($LINES 行)"
